// <auto-generated />
namespace CONTEXTO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initial23 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial23));
        
        string IMigrationMetadata.Id
        {
            get { return "202210192350475_initial23"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
